# -*- coding: utf-8 -*-
"""Sale Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uuoaK-6fRBMDMTJW305CJbZG2oKGaHpw

# **House Sales in King County, USA**

nstructions
In this assignment, you are a Data Analyst working at a Real Estate Investment Trust. The Trust would like to start investing in Residential real estate. You are tasked with determining the market price of a house given a set of features. You will analyze and predict housing prices using attributes or features such as square footage, number of bedrooms, number of floors, and so on. This is a template notebook; your job is to complete the ten questions. Some hints to the questions are given.

As you are completing this notebook, take and save the screenshots of the final outputs of your solutions (e.g., final charts, tables, calculation results etc.). They will need to be shared in the following Peer Review section of the Final Project module.

**About the Dataset**

This dataset contains house sale prices for King County, which includes Seattle. It includes homes sold between May 2014 and May 2015. It was taken from here. It was also slightly modified for the purposes of this course.

| Variable      | Description                                                                                                 |
| ------------- | ----------------------------------------------------------------------------------------------------------- |
| id            | A notation for a house                                                                                      |
| date          | Date house was sold                                                                                         |
| price         | Price is prediction target                                                                                  |
| bedrooms      | Number of bedrooms                                                                                          |
| bathrooms     | Number of bathrooms                                                                                         |
| sqft_living   | Square footage of the home                                                                                  |
| sqft_lot      | Square footage of the lot                                                                                   |
| floors        | Total floors (levels) in house                                                                              |
| waterfront    | House which has a view to a waterfront                                                                      |
| view          | Has been viewed                                                                                             |
| condition     | How good the condition is overall                                                                           |
| grade         | overall grade given to the housing unit, based on King County grading system                                |
| sqft_above    | Square footage of house apart from basement                                                                 |
| sqft_basement | Square footage of the basement                                                                              |
| yr_built      | Built Year                                                                                                  |
| yr_renovated  | Year when house was renovated                                                                               |
| zipcode       | Zip code                                                                                                    |
| lat           | Latitude coordinate                                                                                         |
| long          | Longitude coordinate                                                                                        |
| sqft_living15 | Living room area in 2015(implies-- some renovations) This might or might not have affected the lotsize area |
| sqft_lot15    | LotSize area in 2015(implies-- some renovations)                                                            |

# **Importing Libraries & Setup**

In this section, necessary libraries for data analysis, visualization, and machine learning are imported. Warnings are suppressed to ensure a cleaner output.
"""

# Surpress warnings:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

import warnings
warnings.filterwarnings('ignore')

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import LinearRegression

# %matplotlib inline

"""# **Load Dataset & Preview**

The dataset is loaded from an external source and inspected to understand its structure and variables.

The dataset contains housing features such as size, number of rooms, and location, which will be used to predict house prices.
"""

filepath = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/FinalModule_Coursera/data/kc_house_data_NaN.csv"

df = pd.read_csv(filepath)

df.head()

"""# **Data Types (df.dtypes)**

The data types of each variable are examined to identify numerical and categorical features.

What it does:

Shows column types

Interpretation:

Most variables are numerical, making them suitable for regression analysis. The date column is an object and may require transformation if used.
"""

df.dtypes

print(df.dtypes)

"""# **Statistical Summary (describe())**

A statistical summary is generated to understand the distribution, central tendency, and spread of the data.


The average house price is around 540,000, with a wide range, indicating significant variation in the dataset.
"""

df.describe()

"""Question 2

# **Drop Irrelevant Columns**

Irrelevant features such as ID are removed, as they do not contribute to price prediction.

Removing non-informative variables improves model performance and reduces complexity.
"""

df.drop(["id", "Unnamed: 0"], axis=1, inplace=True)

"""# **Handling Missing Values**

Missing values in key variables such as bedrooms and bathrooms are handled using mean imputation.

This ensures the dataset is complete and prevents errors during model training.
"""

print("number of NaN values for the column bedrooms :", df['bedrooms'].isnull().sum())
print("number of NaN values for the column bathrooms :", df['bathrooms'].isnull().sum())

mean_bedrooms = df['bedrooms'].mean()
df['bedrooms'].fillna(mean_bedrooms, inplace=True)

print("number of NaN values for the column bedrooms :", df['bedrooms'].isnull().sum())
print("number of NaN values for the column bathrooms :", df['bathrooms'].isnull().sum())

"""# **Floors Distribution**

The distribution of the number of floors is analyzed to understand housing structure patterns.

Most houses have 1 or 2 floors, indicating typical residential structures.
"""

floor_counts = df["floors"].value_counts().to_frame()
floor_counts

"""# **Waterfront vs Price (Boxplot)**

A boxplot is used to compare house prices based on whether the property has a waterfront view.


Houses with a waterfront view have significantly higher median prices, indicating that location and view strongly impact property value.
"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(x="waterfront", y="price", data=df)

plt.title("House Prices by Waterfront View")
plt.show()

"""# **Sqft Above vs Price (Regplot)**

A regression plot is used to examine the relationship between living space above ground and house price.

There is a clear positive relationship, suggesting that larger living areas lead to higher prices.
"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.regplot(x="sqft_above", y="price", data=df)

plt.title("Price vs Sqft Above")
plt.show()

df_numeric = df.select_dtypes(include=[np.number])
df_numeric.corr()['price'].sort_values(ascending=False)

"""# **Linear Regression (long → price)**

A simple linear regression model is built using longitude as a predictor.

The very low R² (~0.0004) indicates that longitude alone has almost no predictive power.
"""

from sklearn.linear_model import LinearRegression

X = df[['long']]
Y = df['price']

lm = LinearRegression()
lm.fit(X, Y)

lm.score(X, Y)

"""# **Linear Regression (sqft_living → price)**

A linear regression model is built using living area as the predictor.

The R² (~0.49) shows that nearly half of the variance in price can be explained by living space alone.
"""

from sklearn.linear_model import LinearRegression

X = df[['sqft_living']]
Y = df['price']

lm = LinearRegression()
lm.fit(X, Y)

lm.score(X, Y)

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import LinearRegression

Input = [
    ('scale', StandardScaler()),
    ('polynomial', PolynomialFeatures(include_bias=False)),
    ('model', LinearRegression())
]

from sklearn.model_selection import train_test_split

features = ["floors", "waterfront","lat","bedrooms","sqft_basement",
            "view","bathrooms","sqft_living15","sqft_above","grade","sqft_living"]

X = df[features]
Y = df['price']

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.15, random_state=1)

print("number of test samples:", x_test.shape[0])
print("number of training samples:", x_train.shape[0])

"""# **Heatmap**

A heatmap visualizes correlations between all numerical variables.

Strong relationships are observed between price and size-related features, confirming earlier findings.
"""

plt.figure(figsize=(12,8))

corr = df.corr(numeric_only=True)

sns.heatmap(corr, annot=False, cmap="coolwarm")

plt.title("Correlation Heatmap")
plt.show()

"""# **Top Features Bar Plot**

The most influential features affecting house price are visualized.

Living area, grade, and above-ground space are the most significant predictors.
"""

corr_price = df_numeric.corr()['price'].sort_values(ascending=False)

corr_price = corr_price.drop('price')  # remove self-correlation

plt.figure(figsize=(10,6))
corr_price.head(10).plot(kind='bar')

plt.title("Top 10 Features Correlated with Price")
plt.ylabel("Correlation")
plt.xticks(rotation=45)

plt.show()

"""# **Price Distribution**


The distribution of house prices is examined.

The histogram shows a strongly right-skewed (positively skewed) distribution. This has several important statistical implications:

1. Skewness and Central Tendency
The bulk of observations is concentrated at lower price levels, with a long tail extending to very high values.

This implies:

mean>median>mode

A small number of very expensive houses pull the mean upward, making it non-representative of the typical case.
"""

plt.figure(figsize=(8,5))

sns.histplot(df['price'], kde=True)

plt.title("Distribution of House Prices")
plt.xlabel("Price")

plt.show()

"""# **Scatter Plot (sqft_living vs price)**

A scatter plot visualizes the relationship between house size and price.

A strong upward trend confirms that larger houses tend to be more expensive.
"""

plt.figure(figsize=(8,5))

sns.scatterplot(x="sqft_living", y="price", data=df)

plt.title("Price vs Sqft Living")

plt.show()

"""# **Regression Plot (Improved)**

A regression line is added to better understand the relationship between size and price.

The linear trend confirms a strong positive correlation between living space and price.
"""

plt.figure(figsize=(8,5))

sns.regplot(x="sqft_living", y="price", data=df, scatter_kws={'alpha':0.3})

plt.title("Regression: Price vs Sqft Living")

plt.show()

"""# **Grade vs Price (Boxplot)**

The relationship between house grade and price is analyzed.

Higher-grade houses have significantly higher prices, indicating quality strongly influences value.
"""

plt.figure(figsize=(10,6))

sns.boxplot(x="grade", y="price", data=df)

plt.title("Price Distribution by House Grade")

plt.show()

"""# **Log Transformation**

A logarithmic transformation is applied to reduce skewness in the price distribution.

The transformed distribution becomes more normal, improving model performance.
"""

import numpy as np

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df['log_price'] = np.log(df['price'])

plt.figure(figsize=(8,5))
sns.histplot(df['log_price'], kde=True)

plt.title("Log-Transformed Price Distribution")
plt.show()

"""# **Before vs After**

The original and transformed price distributions are compared.

Log transformation reduces extreme values and creates a more symmetric distribution.
"""

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
sns.histplot(df['price'], kde=True)
plt.title("Original Price")

plt.subplot(1,2,2)
sns.histplot(df['log_price'], kde=True)
plt.title("Log Price")

plt.show()

"""# **Pipeline Model**

A machine learning pipeline is built to automate preprocessing and modeling steps.

The pipeline improves robustness by handling missing values, scaling data, and applying regularization.
"""

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import Ridge
from sklearn.impute import SimpleImputer

features = ["floors", "waterfront","lat","bedrooms","sqft_basement",
            "view","bathrooms","sqft_living15","sqft_above","grade","sqft_living"]

X = df[features]
Y = df['price']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.15, random_state=1)

pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),   # handles NaN
    ('scaler', StandardScaler()),                  # normalize
    ('poly', PolynomialFeatures(degree=2, include_bias=False)),  # interactions
    ('model', Ridge(alpha=0.1))                    # model
])

pipe.fit(x_train, y_train)

"""# **Model Evaluation**

The model is evaluated using R² on both training and test data.

A smaller gap between train and test R² indicates good generalization performance.
"""

print("Train R²:", pipe.score(x_train, y_train))
print("Test R²:", pipe.score(x_test, y_test))

from sklearn.model_selection import cross_val_score

scores = cross_val_score(pipe, X, Y, cv=5)

print("Cross-validation scores:", scores)
print("Average CV score:", scores.mean())

y_pred = pipe.predict(x_test)

plt.figure(figsize=(8,5))

sns.scatterplot(x=y_test, y=y_pred, alpha=0.4)

plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")

plt.title("Actual vs Predicted Prices")

plt.show()

residuals = y_test - y_pred

plt.figure(figsize=(8,5))

sns.scatterplot(x=y_pred, y=residuals, alpha=0.4)

plt.axhline(0, linestyle='--')

plt.xlabel("Predicted Price")
plt.ylabel("Residuals")

plt.title("Residual Plot")

plt.show()

model = pipe.named_steps['model']
feature_names = pipe.named_steps['poly'].get_feature_names_out(features)

coeffs = pd.Series(model.coef_, index=feature_names)

top_features = coeffs.abs().sort_values(ascending=False).head(10)

top_features.plot(kind='bar')

plt.title("Top Influential Features")
plt.show()

"""# **Conclusion**


The analysis shows that house prices are primarily driven by property size and quality. Models using multiple features significantly outperform single-variable models. The use of pipelines and regularization ensures robust and reliable predictions.
"""